# Generated by Django 3.1.1 on 2020-09-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='树名')),
                ('age', models.IntegerField()),
                ('kind', models.CharField(max_length=100, verbose_name='树种')),
            ],
            options={
                'verbose_name': '树先生',
                'verbose_name_plural': '树先生',
                'db_table': 'tree',
            },
        ),
    ]
