# Generated by Django 2.0.6 on 2020-09-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'show_user',
            },
        ),
    ]
